import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { getCachedOsv } from './osvApi'
import { chartRefs } from '../components/Charts'

export async function exportPdf(report, onStart, onDone) {
  onStart?.()

  // Small delay to let the overlay render before blocking
  await new Promise((r) => setTimeout(r, 50))

  try {
    const doc = new jsPDF('p', 'mm', 'a4')
    const pageW = doc.internal.pageSize.getWidth()
    const pageH = doc.internal.pageSize.getHeight()
    const margin = 15
    const contentW = pageW - margin * 2
    const now = new Date()
    const dateStr = now.toISOString().split('T')[0]
    const timestamp = now.toLocaleString()

    const addFooter = (doc) => {
      const pageCount = doc.internal.getNumberOfPages()
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(120)
        doc.text('Generated by Vanir Report Analyzer', margin, pageH - 8)
        doc.text(`Page ${i} of ${pageCount}`, pageW / 2, pageH - 8, { align: 'center' })
        doc.text(timestamp, pageW - margin, pageH - 8, { align: 'right' })
      }
    }

    // --- Cover page ---
    doc.setFillColor(15, 17, 23)
    doc.rect(0, 0, pageW, pageH, 'F')

    doc.setFontSize(32)
    doc.setTextColor(127, 119, 221)
    doc.text('Vanir Security Report', pageW / 2, 60, { align: 'center' })

    doc.setFontSize(12)
    doc.setTextColor(180)
    doc.text(`Scan date: ${dateStr}`, pageW / 2, 80, { align: 'center' })

    if (report.options) {
      doc.setFontSize(9)
      doc.setTextColor(150)
      const optLines = doc.splitTextToSize(`Command: ${report.options}`, contentW)
      doc.text(optLines, pageW / 2, 92, { align: 'center' })
    }

    const { metrics } = report
    const summaryY = 120

    const summaryItems = [
      ['Unpatched CVEs', metrics.totalUnpatched],
      ['Covered CVEs', metrics.totalCovered],
      ['Direct Matches', metrics.directMatches],
      ['Non-target Only', metrics.nonTargetOnly],
    ]

    const boxW = 40
    const gap = 5
    const totalBoxW = summaryItems.length * boxW + (summaryItems.length - 1) * gap
    let startX = (pageW - totalBoxW) / 2

    for (const [label, value] of summaryItems) {
      doc.setFillColor(26, 29, 46)
      doc.roundedRect(startX, summaryY, boxW, 28, 3, 3, 'F')
      doc.setFontSize(20)
      doc.setTextColor(127, 119, 221)
      doc.text(String(value), startX + boxW / 2, summaryY + 13, { align: 'center' })
      doc.setFontSize(7)
      doc.setTextColor(180)
      doc.text(label, startX + boxW / 2, summaryY + 22, { align: 'center' })
      startX += boxW + gap
    }

    // --- Page 2: Executive Summary with charts ---
    doc.addPage()
    doc.setFillColor(255, 255, 255)
    doc.rect(0, 0, pageW, pageH, 'F')

    doc.setFontSize(18)
    doc.setTextColor(30)
    doc.text('Executive Summary', margin, 20)

    let chartY = 32

    // Grab chart images directly from the Chart.js canvas via toBase64Image
    const charts = [
      { ref: chartRefs.donut, title: 'CVEs by Component' },
      { ref: chartRefs.year, title: 'CVEs by Year' },
    ]

    for (const { ref, title } of charts) {
      const chart = ref // this is the react-chartjs-2 ref which has a .canvas
      if (!chart) continue

      // Draw title
      doc.setFontSize(11)
      doc.setTextColor(60)
      doc.text(title, margin, chartY)
      chartY += 4

      const imgData = chart.toBase64Image('image/png', 1)
      const canvas = chart.canvas
      const aspectRatio = canvas.height / canvas.width
      const imgW = contentW
      const imgH = imgW * aspectRatio
      const fitH = Math.min(imgH, 110)

      if (chartY + fitH > pageH - 20) {
        doc.addPage()
        doc.setFillColor(255, 255, 255)
        doc.rect(0, 0, pageW, pageH, 'F')
        chartY = 20
      }

      doc.addImage(imgData, 'PNG', margin, chartY, imgW, fitH)
      chartY += fitH + 12
    }

    // --- Pages 3+: CVE table ---
    doc.addPage()

    const tableData = report.cves.map((cve) => {
      const osv = getCachedOsv(cve.asbId)
      return [
        cve.cveId,
        osv?.severityLabel || '—',
        cve.components.join(', '),
        cve.matchType,
        String(cve.details.length),
        osv?.summary ? osv.summary.substring(0, 80) : '—',
      ]
    })

    autoTable(doc, {
      head: [['CVE ID', 'Severity', 'Component(s)', 'Match Type', 'Files', 'Description']],
      body: tableData,
      startY: 15,
      styles: {
        fontSize: 7,
        cellPadding: 2,
        textColor: [30, 30, 30],
        lineWidth: 0.1,
        lineColor: [200, 200, 200],
      },
      headStyles: {
        fillColor: [127, 119, 221],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [245, 245, 250],
      },
      columnStyles: {
        0: { cellWidth: 28, font: 'courier' },
        1: { cellWidth: 18 },
        2: { cellWidth: 30 },
        3: { cellWidth: 20 },
        4: { cellWidth: 12 },
        5: { cellWidth: 'auto' },
      },
      margin: { left: margin, right: margin },
      showHead: 'everyPage',
    })

    addFooter(doc)
    doc.save(`vanir-report-${dateStr}.pdf`)
  } finally {
    onDone?.()
  }
}
